version: '3'

volumes:
  production_postgres_data: { }
  production_postgres_data_backups: { }

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: happy_dogs_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    ports:
      - "80:5000"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: happy_dogs_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres
