# Generated by Django 3.1.13 on 2021-10-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visit',
            new_name='BoardingVisit',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='dog',
            name='last_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dog',
            unique_together={('first_name', 'last_name')},
        ),
    ]
